<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sobee.Common\Sobee.Common.csproj" />
    <ProjectReference Include="..\Sobee.Network\Sobee.Network.csproj" />
    <ProjectReference Include="..\Sobee.Serialization\Sobee.Serialization.csproj" />
    <ProjectReference Include="..\Sobee.Tasks\Sobee.Tasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SocketMessageHandler.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

</Project>
