<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Football.GameServer.Messages\Football.GameServer.Messages.csproj" />
    <ProjectReference Include="..\Football.Network\Football.Network.csproj" />
    <ProjectReference Include="..\Football.Serialization\Football.Serialization.csproj" />
    <ProjectReference Include="..\Football.GameServer.Messages\Football.GameServer.Messages.csproj" />
    <ProjectReference Include="..\Football.Network\Football.Network.csproj" />
  </ItemGroup>

</Project>
