<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sobee.Common\Sobee.Common.csproj" />
    <ProjectReference Include="..\Sobee.Messaging\Sobee.Messaging.csproj" />
    <ProjectReference Include="..\Sobee.Network\Sobee.Network.csproj" />
  </ItemGroup>

</Project>
